name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]  # You can adjust the Node.js version based on your requirements

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build --if-present

    - name: Run Tests
      run: npm test

    - name: Update Angular CLI
      run: npm install @angular/cli@latest

    - name: Resolve Dependencies
      run: npm audit fix --force --engine-strict-semver=false

    - name: Final Build
      run: npm run build --if-present

    - name: Final Tests
      run: npm test
